# Generated by Django 3.0.6 on 2021-04-19 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('student_id', models.AutoField(primary_key=True, serialize=False)),
                ('fullname', models.CharField(max_length=50, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('git_name', models.CharField(max_length=32, unique=True)),
                ('slack_email', models.EmailField(max_length=128, unique=True)),
                ('atl_account', models.CharField(max_length=32, unique=True)),
            ],
            options={
                'db_table': 'student',
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('team_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64, unique=True)),
                ('subject_code', models.CharField(max_length=128)),
                ('supervisor_id', models.IntegerField()),
                ('secondary_supervisor_id', models.IntegerField()),
                ('year', models.IntegerField()),
                ('create_date', models.BigIntegerField()),
                ('project_name', models.CharField(max_length=64)),
                ('slack_oauth_token', models.CharField(max_length=100)),
                ('sprint_start_0', models.BigIntegerField()),
                ('sprint_end_0', models.BigIntegerField()),
                ('sprint_start_1', models.BigIntegerField()),
                ('sprint_end_1', models.BigIntegerField()),
                ('sprint_start_2', models.BigIntegerField()),
                ('sprint_end_2', models.BigIntegerField()),
                ('sprint_start_3', models.BigIntegerField()),
                ('sprint_end_3', models.BigIntegerField()),
                ('sprint_start_4', models.BigIntegerField()),
                ('sprint_end_4', models.BigIntegerField()),
            ],
            options={
                'db_table': 'team',
            },
        ),
        migrations.CreateModel(
            name='TeamConfiguration',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('team_id', models.IntegerField()),
                ('slack_access', models.IntegerField()),
                ('slack_workspace', models.CharField(max_length=128)),
                ('slack_token', models.CharField(max_length=128)),
                ('confluence_workspace', models.CharField(max_length=128)),
                ('jira_workspace', models.CharField(max_length=128)),
                ('git_repository', models.CharField(max_length=128)),
            ],
            options={
                'db_table': 'team_configuration',
            },
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('member_id', models.AutoField(primary_key=True, serialize=False)),
                ('student_id', models.IntegerField()),
                ('team_id', models.IntegerField()),
            ],
            options={
                'db_table': 'team_member',
            },
        ),
    ]
