# Generated by Django 3.0.6 on 2021-05-06 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IndividualContributions',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('student', models.CharField(max_length=256)),
                ('done_count', models.IntegerField()),
            ],
            options={
                'db_table': 'individualContributions',
            },
        ),
        migrations.CreateModel(
            name='JiraCountByTime',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('space_key', models.CharField(max_length=256)),
                ('count_time', models.CharField(max_length=256)),
                ('todo', models.IntegerField()),
                ('in_progress', models.IntegerField()),
                ('done', models.IntegerField()),
            ],
            options={
                'db_table': 'jiraCountByTime',
            },
        ),
        migrations.CreateModel(
            name='Urlconfig',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('space_key', models.CharField(max_length=256)),
                ('jira_url', models.CharField(max_length=256)),
                ('git_url', models.CharField(max_length=256)),
            ],
            options={
                'db_table': 'url_config',
            },
        ),
    ]
