# Generated by Django 3.0.6 on 2021-04-27 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jira',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.IntegerField()),
                ('message', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'jira',
            },
        ),
    ]
