# Generated by Django 3.0.6 on 2021-04-28 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jira', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Jira',
            new_name='TestJira',
        ),
    ]
