# Generated by Django 3.0.6 on 2021-04-29 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jira', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='JiraCountByTime',
        ),
    ]
