# Generated by Django 3.0.6 on 2021-04-29 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jira', '0002_delete_jiracountbytime'),
    ]

    operations = [
        migrations.CreateModel(
            name='JiraCountByTime',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('time', models.CharField(max_length=256)),
                ('todo', models.IntegerField()),
                ('in_progress', models.IntegerField()),
                ('done', models.IntegerField()),
            ],
            options={
                'db_table': 'jiraCountByTime',
            },
        ),
    ]
