# Generated by Django 3.0.6 on 2021-05-09 06:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('jira', '0002_individualcontributions_space_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='urlconfig',
            name='git_password',
            field=models.CharField(default=django.utils.timezone.now, max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='urlconfig',
            name='git_username',
            field=models.CharField(default=django.utils.timezone.now, max_length=256),
            preserve_default=False,
        ),
    ]
