# Generated by Django 3.0.6 on 2021-04-29 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jira', '0003_jiracountbytime'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jiracountbytime',
            old_name='time',
            new_name='count_time',
        ),
    ]
