# Generated by Django 3.0.6 on 2021-04-29 12:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('jira', '0004_auto_20210429_2231'),
    ]

    operations = [
        migrations.AddField(
            model_name='jiracountbytime',
            name='space_key',
            field=models.CharField(default=django.utils.timezone.now, max_length=256),
            preserve_default=False,
        ),
    ]
