# Generated by Django 3.0.6 on 2021-05-27 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jira', '0004_auto_20210519_2302'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jiracountbytime',
            old_name='count_time',
            new_name='time',
        ),
        migrations.RenameField(
            model_name='jiracountbytime',
            old_name='todo',
            new_name='to_do',
        ),
    ]
