# Generated by Django 3.0.6 on 2021-04-30 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jira', '0005_jiracountbytime_space_key'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndividualContributions',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('student', models.CharField(max_length=256)),
                ('done', models.IntegerField()),
            ],
            options={
                'db_table': 'individualContributions',
            },
        ),
    ]
