# Generated by Django 3.0.6 on 2021-04-30 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jira', '0007_auto_20210430_1248'),
    ]

    operations = [
        migrations.CreateModel(
            name='Urlconfig',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('space_key', models.CharField(max_length=256)),
                ('jira_url', models.CharField(max_length=256)),
                ('git_url', models.CharField(max_length=256)),
            ],
            options={
                'db_table': 'url_config',
            },
        ),
    ]
