# Generated by Django 3.0.6 on 2021-05-15 02:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coordinator', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coordinator',
            name='git_password',
        ),
        migrations.RemoveField(
            model_name='coordinator',
            name='git_username',
        ),
    ]
