# Generated by Django 3.0.6 on 2021-05-17 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coordinator', '0002_auto_20210515_1014'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coordinator',
            name='atl_password',
        ),
        migrations.RemoveField(
            model_name='coordinator',
            name='atl_username',
        ),
    ]
