# Generated by Django 3.0.6 on 2021-05-15 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_auto_20210428_1431'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectcoordinatorrelation',
            name='git_password',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AddField(
            model_name='projectcoordinatorrelation',
            name='git_username',
            field=models.CharField(default='', max_length=256),
        ),
    ]
