# Generated by Django 3.0.6 on 2021-04-28 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PageHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_count', models.IntegerField()),
                ('date', models.IntegerField()),
                ('space_key', models.CharField(max_length=256)),
            ],
            options={
                'db_table': 'page_history',
            },
        ),
    ]
