# Generated by Django 3.0.6 on 2021-04-26 03:08

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True
    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=256)),
                ('user_name', models.CharField(max_length=256)),
                ('email', models.EmailField(max_length=256)),
                ('picture', models.CharField(max_length=256)),
                ('space_key', models.CharField(max_length=256)),
            ],
            options={
                'db_table': 'user_list',
            },
        ),

        migrations.CreateModel(
            name='PageHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_count', models.IntegerField()),
                ('date', models.IntegerField()),
                ('space_key', models.CharField(max_length=256)),
            ],
            options={
                'db_table': 'page_history',
            },
        ),
    ]