# Generated by Django 3.0.6 on 2021-05-09 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MeetingMinutes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meeting_title', models.CharField(max_length=256)),
                ('meeting_link', models.TextField()),
                ('space_key', models.CharField(max_length=256)),
            ],
            options={
                'db_table': 'meeting_minutes',
            },
        ),
        migrations.CreateModel(
            name='PageHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_count', models.IntegerField()),
                ('date', models.IntegerField()),
                ('space_key', models.CharField(max_length=256)),
            ],
            options={
                'db_table': 'page_history',
            },
        ),
        migrations.CreateModel(
            name='UserList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=256)),
                ('user_name', models.CharField(max_length=256)),
                ('email', models.EmailField(max_length=256)),
                ('picture', models.CharField(max_length=256)),
                ('space_key', models.CharField(max_length=256)),
            ],
            options={
                'db_table': 'user_list',
            },
        ),
    ]
