# Generated by Django 3.0.6 on 2021-05-02 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('confluence', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeetingMinutes',
            fields=[
                ('meeting_id', models.IntegerField(primary_key=True, serialize=False)),
                ('meeting_title', models.CharField(max_length=256)),
                ('meeting_link', models.TextField()),
                ('space_key', models.CharField(max_length=256)),
            ],
            options={
                'db_table': 'meeting_minutes',
            },
        ),
    ]
