# Generated by Django 3.0.6 on 2021-05-09 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('confluence', '0002_meetingminutes'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndividualConfluenceContribution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('space_key', models.CharField(max_length=256)),
                ('user_name', models.CharField(max_length=256)),
                ('page_count', models.IntegerField()),
            ],
            options={
                'db_table': 'individual_confluence_contribution',
            },
        ),
    ]
