# Generated by Django 3.0.6 on 2021-05-17 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('confluence', '0003_individualconfluencecontribution'),
    ]

    operations = [
        migrations.AddField(
            model_name='individualconfluencecontribution',
            name='user_id',
            field=models.CharField(default=1, max_length=256),
            preserve_default=False,
        ),
    ]
