# Generated by Django 3.0.6 on 2021-05-19 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('confluence', '0004_individualconfluencecontribution_user_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MeetingMinutes',
        ),
    ]
