# Generated by Django 3.0.6 on 2021-05-19 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('confluence', '0005_delete_meetingminutes'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeetingMinutes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meeting_title', models.CharField(max_length=256)),
                ('meeting_link', models.TextField()),
                ('space_key', models.CharField(max_length=256)),
            ],
            options={
                'db_table': 'meeting_minutes',
            },
        ),
    ]
