# Generated by Django 3.0.6 on 2021-04-27 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('git', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GitCommitCounts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relation_id', models.CharField(max_length=256)),
                ('space_key', models.CharField(max_length=256)),
                ('commit_counts', models.CharField(max_length=256)),
                ('query_date', models.DateField()),
            ],
            options={
                'db_table': 'git_commit_counts',
            },
        ),
    ]
