# Generated by Django 3.0.6 on 2021-05-20 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('git', '0002_auto_20210507_0645'),
    ]

    operations = [
        migrations.CreateModel(
            name='GitMetrics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('space_key', models.CharField(max_length=256)),
                ('file_count', models.IntegerField()),
                ('class_count', models.IntegerField()),
                ('function_count', models.IntegerField()),
                ('code_lines_count', models.IntegerField()),
                ('declarative_lines_count', models.IntegerField()),
                ('executable_lines_count', models.IntegerField()),
                ('comment_lines_count', models.IntegerField()),
                ('comment_to_code_ratio', models.FloatField()),
            ],
            options={
                'db_table': 'git_metrics',
            },
        ),
    ]
