# Generated by Django 3.0.6 on 2021-04-29 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('git', '0002_gitcommitcounts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gitcommitcounts',
            name='relation_id',
        ),
        migrations.AlterField(
            model_name='gitcommitcounts',
            name='query_date',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='studentcommitcounts',
            name='relation_id',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='studentcommitcounts',
            name='space_key',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
