# Generated by Django 3.0.6 on 2021-04-19 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('invitation_id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('key', models.CharField(db_index=True, max_length=128, unique=True)),
                ('email', models.CharField(max_length=50)),
                ('template', models.CharField(max_length=1024)),
                ('operator', models.IntegerField()),
                ('create_date', models.BigIntegerField()),
                ('send_date', models.BigIntegerField(null=True)),
                ('accept_reject_date', models.BigIntegerField(null=True)),
                ('expired', models.BigIntegerField(db_index=True)),
                ('status', models.IntegerField()),
            ],
            options={
                'db_table': 'invitation',
            },
        ),
    ]
