# Generated by Django 3.0.6 on 2021-04-19 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('account_id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=32, unique=True)),
                ('email', models.EmailField(max_length=128, unique=True)),
                ('password', models.CharField(max_length=256)),
                ('status', models.IntegerField()),
                ('create_date', models.BigIntegerField()),
                ('update_date', models.BigIntegerField()),
            ],
            options={
                'db_table': 'account',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('account_id', models.IntegerField(db_index=True)),
                ('sso_id', models.BigIntegerField(db_index=True, null=True)),
                ('username', models.CharField(max_length=32, unique=True)),
                ('first_name', models.CharField(max_length=64)),
                ('last_name', models.CharField(max_length=64)),
                ('email', models.CharField(max_length=128)),
                ('atl_username', models.CharField(max_length=128)),
                ('atl_password', models.CharField(max_length=256)),
                ('role', models.IntegerField()),
                ('status', models.IntegerField()),
                ('create_date', models.BigIntegerField()),
                ('update_date', models.BigIntegerField()),
                ('git_username', models.CharField(max_length=128)),
                ('slack_email', models.CharField(max_length=128)),
            ],
            options={
                'db_table': 'user',
            },
        ),
    ]
