# Generated by Django 3.0.6 on 2021-04-19 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SlackMember',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('student_id', models.IntegerField()),
                ('team_id', models.IntegerField()),
                ('channel_name', models.CharField(max_length=50)),
                ('message_num', models.IntegerField()),
                ('sprint_num', models.IntegerField()),
                ('time', models.BigIntegerField()),
            ],
            options={
                'db_table': 'slack_member',
            },
        ),
        migrations.CreateModel(
            name='SlackTeam',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('team_id', models.IntegerField()),
                ('channel_name', models.CharField(max_length=50)),
                ('message_num', models.IntegerField()),
                ('sprint_num', models.IntegerField()),
                ('time', models.BigIntegerField()),
            ],
            options={
                'db_table': 'slack_team',
            },
        ),
    ]
